-- Oracle SQL Schema for Billing System

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) UNIQUE NOT NULL,
  password VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) DEFAULT 'employee',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE customers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) UNIQUE,
  phone VARCHAR2(20),
  address VARCHAR2(4000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(150) NOT NULL,
  description CLOB,
  price NUMBER(10, 2) NOT NULL,
  stock NUMBER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE sales (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER REFERENCES customers(id) ON DELETE SET NULL,
  user_id NUMBER REFERENCES users(id) ON DELETE SET NULL,
  total_amount NUMBER(10, 2) NOT NULL,
  status VARCHAR2(50) DEFAULT 'unpaid',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE sale_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id NUMBER REFERENCES sales(id) ON DELETE CASCADE,
  product_id NUMBER REFERENCES products(id),
  quantity NUMBER NOT NULL,
  price_at_time NUMBER(10, 2) NOT NULL
);
/

CREATE TABLE suppliers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  contact_person VARCHAR2(100),
  email VARCHAR2(100),
  phone VARCHAR2(20),
  address VARCHAR2(4000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE purchase_orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id NUMBER REFERENCES suppliers(id) ON DELETE SET NULL,
  user_id NUMBER REFERENCES users(id) ON DELETE SET NULL,
  total_amount NUMBER(10, 2) DEFAULT 0.00 NOT NULL,
  status VARCHAR2(50) DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE purchase_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id NUMBER REFERENCES purchase_orders(id) ON DELETE CASCADE,
  product_id NUMBER REFERENCES products(id),
  quantity NUMBER NOT NULL,
  cost_price NUMBER(10, 2) NOT NULL
);
/

CREATE TABLE invoices (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id NUMBER REFERENCES sales(id) ON DELETE CASCADE,
  invoice_number VARCHAR2(100) UNIQUE NOT NULL,
  status VARCHAR2(50) DEFAULT 'Unpaid',
  issue_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  due_date TIMESTAMP
);
/

CREATE TABLE payments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id NUMBER REFERENCES invoices(id) ON DELETE CASCADE,
  amount NUMBER(10, 2) NOT NULL,
  payment_method VARCHAR2(50) NOT NULL,
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE discounts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  type VARCHAR2(20) NOT NULL,
  value NUMBER(10, 2) NOT NULL,
  active NUMBER(1) DEFAULT 1, -- Using 1 for true
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE TABLE inventory_transactions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id NUMBER REFERENCES products(id) ON DELETE CASCADE,
  transaction_type VARCHAR2(20) NOT NULL,
  quantity NUMBER NOT NULL,
  reference_id NUMBER,
  notes VARCHAR2(4000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

-- Procedues & Functions
CREATE OR REPLACE PROCEDURE adjust_stock(p_product_id IN NUMBER, p_quantity IN NUMBER) IS
BEGIN
    UPDATE products SET stock = stock + p_quantity WHERE id = p_product_id;
END;
/

CREATE OR REPLACE FUNCTION get_total_sale_amount(p_sale_id IN NUMBER) RETURN NUMBER IS
    v_total NUMBER;
BEGIN
    SELECT SUM(quantity * price_at_time) INTO v_total FROM sale_items WHERE sale_id = p_sale_id;
    RETURN NVL(v_total, 0);
END;
/

-- Triggers
CREATE OR REPLACE TRIGGER trg_update_stock_on_sale
AFTER INSERT ON sale_items
FOR EACH ROW
BEGIN
    adjust_stock(:NEW.product_id, -:NEW.quantity);
END;
/

CREATE OR REPLACE TRIGGER trg_update_stock_on_inventory
AFTER INSERT ON inventory_transactions
FOR EACH ROW
BEGIN
    IF :NEW.transaction_type = 'IN' THEN
        adjust_stock(:NEW.product_id, :NEW.quantity);
    ELSIF :NEW.transaction_type = 'OUT' THEN
        adjust_stock(:NEW.product_id, -:NEW.quantity);
    END IF;
END;
/

